spring.application.name=ShipmentScaler

# Enable the H2 web console at http://localhost:8080/h2-console
spring.h2.console.enabled=true

# Force Spring Boot to run schema.sql and data.sql on startup
spring.sql.init.mode=always
spring.sql.init.platform=h2

# In-memory database connection string
spring.datasource.url=jdbc:h2:mem:shipmentScalerDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Debug Logs
logging.level.sql=debug
logging.level.org.springframework.test.context.transaction.TransactionContext=debug

# JPA/Hybernate DDL Auto Flag
spring.jpa.hibernate.ddl-auto=update